### ISSUE TITLE
Hog pauses need documentation

### ISSUE THREAD

**Issue by thisfinalcode** [Nickles255/Assignment4_Hog_game#3]
In branch Hog_K_ver, Hog.java needs documentation for the sleep methods

            try {Thread.sleep(250);
              } catch (Exception e) {}

      try {Thread.sleep(300);
      } catch (Exception e) {}

**Comment by Nickles255** [comment]
Added comment. The pause is in milliseconds but was just enough to create some separation between key points in the round.
