### ISSUE TITLE
Hog in Hog_K_ver can use myRound.toString

### ISSUE THREAD

**Issue by thisfinalcode** [Nickles255/Assignment4_Hog_game#4]
In Hog.java, use myRound.toString instead of re-writing the function:

        if(myRound.getStopInd() == false){
           myRound.addRoundScore(diePair.sumDice());
           System.out.println("Round Score: " + myRound.getRoundScore());
           System.out.println("Potential Score: " + myRound.getPotentialTotal());
           System.out.println("\n");

**Comment by Nickles255** [comment]
Modified Hog.java using toString function in Round class. Done!
Thanks for the suggestion.
