### ISSUE TITLE
assignment zip file needs both the java AND class files

### ISSUE THREAD

**Issue by thisfinalcode** [Nickles255/Assignment4_Hog_game#5]
Please make sure all request files are included in the zip file.
Her instructions for submission were:

Once you have the code working on your own machine, you must submit your assignment on Canvas (to avoid late penalty submission must be completed no later than 5pm on due date). 
Check you have provided algorithm (in comment at top of driver file) and used javadoc style comments.  See link on homepage "How Programming Assignments Are Graded".

a) zip your 3 source code and 3 byte code files into an archive named Assignment4.zip

- Hog.java, Die.java, and PairOfDice.java 
- Hog.class, Die.class, and PairOfDice.class

**Comment by Nickles255** [comment]
Doing that now.

**Comment by Nickles255** [comment]
Zipped updated Java and Class files into single zip file
