### ISSUE TITLE
In PairOfDie, constructor to initialize each die to 1

### ISSUE THREAD

**Issue by thisfinalcode** [Nickles255/Assignment4_Hog_game#6]
Step 1)
Using the Die class defined in Chapter 4, write a class called PairOfDice, composed of two Die objects. Include methods to set and get each of the individual die values, a method to roll the two die, and a method that returns the current sum of the two die values. **The constructor should initialize each die to 1.**
Create a driver class called RollingDice2 to instantiate and use a PairOfDice object.

**Comment by thisfinalcode** [comment]
i guess Die already initializes its face value to 1... not sure what she means??

**Comment by thisfinalcode** [comment]
but in another sense, i guess our currentTotal should really be initialized to die1.getFaceValue() + die2.getFaceValue() instead of directly setting it to 2?

---------------------------------
  public PairOfDie() {
    currentTotal = 2;
  }

**Comment by Nickles255** [comment]
I left currentTotal as 2 and also set die1 and die2 to 1 in the code.

**Comment by thisfinalcode** [comment]
die 2 is being set to 2...

  public PairOfDice() {
    currentTotal = 2;
	die1.setFaceValue(1);
	die2.setFaceValue(2);
  }

**Comment by Nickles255** [comment]
corrected that. well I think your way is better I will change in a sec. Should have been more careful about my PairOfDice class.

**Comment by Nickles255** [comment]
modified constructor to store initialized total as

 die1.getFaceValue() + die2.getFaceValue()
