### ISSUE TITLE
RollingDice2 class?

### ISSUE THREAD

**Issue by thisfinalcode** [Nickles255/Assignment4_Hog_game#8]
Not sure if this is a type from the professor, but she says that she wants a RollingDice2 class? Maybe she meant Die class as the Driver?

Step 1)
Using the Die class defined in Chapter 4, write a class called PairOfDice, composed of two Die objects. Include methods to set and get each of the individual die values, a method to roll the two die, and a method that returns the current sum of the two die values. The constructor should initialize each die to 1.
Create a driver class called **RollingDice2** to instantiate and use a PairOfDice object.

**Comment by Nickles255** [comment]
She does not want the RollingDice2 code. She stated that as a good idea. Need to test your PairOfDice class before creating the whole Hog game. So it is more for us.
