### ISSUE TITLE
getDie1 should return Die

### ISSUE THREAD

**Issue by thisfinalcode** [Nickles255/Assignment4_Hog_game#9]
In her instuctions, it sas that that getDie1() and getDie2() should return Die...but we currently have it returning int value:

+ PairOfDice(): PairOfDice
+ getDie1(): Die
+ getDie2(): Die
+ setDie1(int): void
+ setDie2(int): void
+sumDice(): int
+rollDice():int
+toString():String
------------------------------
  public int getDie1() {
    return die1.getFaceValue();
  }

  public int getDie2(){
    return die2.getFaceValue();
  }

**Comment by Nickles255** [comment]
fixed. New PairOfDice class getDie1 and getDie2 both return Die type. 
Modified Hog.java to check for 
diePair.getDie1().getFaceValue() == 1 || diePair.getDie2().getFaceValue() == 1
as an exit point.
